# Tested: 2024/08/05
# by Kasper Arfman
# https://gist.github.com/zl475505/25245e8d28b13b3273e8bae1a63c4af2
name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Caching Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Ensure you are using a compatible Python version

      - name: Install requirements in requirements.txt if it exists
        run: |
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi
        shell: bash

      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake
          sudo apt-get update && sudo apt-get install -y python3-distutils autoconf automake autopoint build-essential ccache cmake gettext git libffi-dev libltdl-dev libssl-dev liblzma-dev libtool openjdk-8-jdk patch pkg-config python3-pip python3-setuptools sudo unzip zip zlib1g-dev
          pip install --user --upgrade Cython virtualenv
          pip install --user --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Handle Java path
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          sudo update-java-alternatives --set ${JAVA_HOME}
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Buildozer build app
        run: yes | buildozer -v android debug || buildozer -v android debug
        # run cmd1 and cmd2 if cmd1 failed
        # yes | buildozer ...  this cmd finish to fail ("yes not recognized") but permits to accept licence,
        # || is used then to re-run buildozer with a licence accepted


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk