# Documentation here: https://github.com/ArtemSBulgakov/buildozer-action
name: Build
# Launch every time `push` action is performed
on: [push]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:

      # Enable checkout and github actions
      - name: Checkout
        uses: actions/checkout@v2
#        with:
#          path: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Ensure you are using a compatible Python version

      - name: Install dependencies
        # run: sudo apt-get update && sudo apt-get install -y gettext
        run: sudo apt-get update && sudo apt-get install -y python3-distutils autoconf automake autopoint build-essential ccache cmake gettext git libffi-dev libltdl-dev libssl-dev liblzma-dev libtool openjdk-8-jdk patch pkg-config python3-pip python3-setuptools sudo unzip zip zlib1g-dev

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install buildozer


      - name: Build with Buildozer
        run: buildozer -v android debug

      # Use an already existing git repo to launch `buildozer build`
      # Use https://github.com/ArtemSBulgakov/buildozer-action/tree/master
#      - name: Build with Buildozer
#        uses: ArtemSBulgakov/buildozer-action@v1
#        id: buildozer
#        with:
#          # repository_root: main
#          workdir: .
#          buildozer_version: stable

      # After last step (APK creation) store it on github.
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}