# Update the badge "version" on readme.md
name: Update Version Badge

on:
  push:
    paths:
      - 'src/__version__.py'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "VERSION=$(grep -oP '(?<=version=).*' src/__version__.py | tr -d '"')" >> $GITHUB_ENV
      - name: Create version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <YOUR_GIST_ID>
          filename: version.json
          label: version
          message: ${{ env.VERSION }}
          color: blue
